### ISSUE TITLE
Unexpected space at find-pkg-share substitution

### ISSUE THREAD

**Issue by Thodoris1999** [ros2/launch#413] opened 2020-05-06 19:29 UTC
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 18.04
- Installation type:
  - Binaries
- Version or commit hash:
  - eloquent
- DDS implementation:
  - doesn't matter probably
- Client library (if applicable):
  - N/A

#### Steps to reproduce issue

1. create a launch file in package "robot-description" (requires gazebo_ros_pkgs) in the form:
<launch>
<node pkg="gazebo_ros" exec="spawn_entity.py" 
  args="-entity turtle -file $(find-pkg-share robot_description)/urdf/turtle.urdf"/>
</launch>
2. run `ros2 launch pkg file.launch.xml`

#### Expected behavior
spawn_entity.py runs (may fail if you do not have a correctly formatted URDF file or gzserver is not running but at least runs). `$(find-pkg-share robot_description)/urdf/turtle.urdf` is substituted with `/home/user/ros_ws/install/robot_description/share/robot_description/urdf/turtle.urdf`

#### Actual behavior
spawn_entity.py fails with
`
spawn_entity.py: error: unrecognized arguments: /urdf/turtle.urdf
`
and prints below the command requested
`
'/opt/ros/eloquent/lib/gazebo_ros/spawn_entity.py -entity turtle -file /home/user/ros_ws/install/robot_description/share/robot_description /urdf/turtle.urdf --ros-args'
`
Notice the space after the substitution. The space tricks spawn_entity.py into thinking /urdf/turtle.urdf is a separate argument. This is not expected and the command runs normally when I run it on the terminal without the space.
#### Additional information
I have not tested this in any other cases, I don't know why it happened here. Other times I have tried this substitution outside the args tag it worked without adding unexpected spaces

**Comment by hidmic** [comment] 2020-05-07 15:21
I believe this is a duplicate of https://github.com/ros2/launch/issues/399, which has been addressed and backported. It'll be included in the next Eloquent patch release and in the upcoming Foxy release.

**Closed by hidmic** 2020-05-07 15:21 UTC
